fix: add typescript definition for this utility
Patreon/url-factory pull request #3
Opened 2022-06-29 21:53 UTC by val-patreon

Internally, Patreon is trying its best to use TypeScript everywhere. However, that's made harder when some of its public  legacy utilities that it imports are not typed.

Relevant functions that I used to derive the type: https://github.com/Patreon/url-factory/blob/b7c275513e0eb1a8ba6a89512979bc298b427292/src/index.js#L6-L43

2022-06-29 21:56 UTC, mathewlee11 commented
TIL this repo exists and I get email notifications for it

2022-06-29 23:46 UTC, anaulin commented
Same, @mathewlee11, same. Turns out https://github.com/watching is our friend.

2022-06-30 15:04 UTC, mathewlee11 commented
@anaulin that is much easier than my current strategy of unsubscribing from repos after the first email!

2022-07-07 18:02 UTC, dorwin-patreon requested changes

2022-07-07 18:02 UTC, dorwin-patreon commented on index.d.ts
> +export default function urlFactory(baseUrl?: string, baseParams?: Record<string, unknown>): ReturnInnerFuction;
the change itself looks good but you should add the `types` key and extend the `files` key in package.json ([example](https://github.com/Patreon/nion/blob/master/package.json#L7-L14))

2022-07-07 19:36 UTC, dorwin-patreon approved these changes

2022-07-07 19:36 UTC, dorwin-patreon commented on types/tsconfig.json
> +        "jsx": "react",
not needed since no react here?

2022-07-07 20:09 UTC, merged